version: '3.8'

services:
  power-grid-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: power-grid-builder
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - power-grid-network
    labels:
      - "com.example.description=Power Grid Builder Game"
      - "com.example.department=Engineering"
      - "com.example.label-with-value=power-grid-builder"

networks:
  power-grid-network:
    driver: bridge
